import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { Toaster } from "sonner";

import ReduxProvideProps from "./ReduxProvier";

import LoadingWrapper from "./LoadingWrapper";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ReduxProvideProps>
          <LoadingWrapper />

          <Toaster />
          <header>
            {" "}
            <Header />
          </header>
          <div className="flex-1 mt-20"> {children}</div>

          <footer>
            <Footer />
          </footer>
        </ReduxProvideProps>
      </body>
    </html>
  );
}
