name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1
          aws sts get-caller-identity
          aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 440744253012.dkr.ecr.ap-south-1.amazonaws.com

      - name: Log in to AWS ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 440744253012.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t 440744253012.dkr.ecr.ap-south-1.amazonaws.com/backendforexfornepal:latest ./server

      - name: Push Docker Image to ECR
        run: |
          docker push 440744253012.dkr.ecr.ap-south-1.amazonaws.com/backendforexfornepal:latest

      # SSH into EC2 and deploy
      - name: Deploy Docker Image to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }} # Your EC2 Public IP or DNS
          username: ubuntu # Default EC2 user for Ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }} # SSH private key from GitHub secrets
          script: |
            # Gracefully stop and remove any existing container using the same image
            CONTAINER_ID=$(sudo docker ps -q --filter ancestor=440744253012.dkr.ecr.ap-south-1.amazonaws.com/backendforexfornepal:latest)
            if [ ! -z "$CONTAINER_ID" ]; then
             sudo docker stop $CONTAINER_ID
             sudo docker rm $CONTAINER_ID
             echo "Stopped and removed existing container $CONTAINER_ID"
            else
             echo "No existing container found"
            fi
            sudo docker system prune -f
             
            if ! sudo docker pull 440744253012.dkr.ecr.ap-south-1.amazonaws.com/backendforexfornepal:latest; then
             echo "Failed to pull Docker image"
             exit 1
            fi

             # Pull the latest Docker image from ECR
             sudo docker pull 440744253012.dkr.ecr.ap-south-1.amazonaws.com/backendforexfornepal:latest

             # Run the new Docker container with the appropriate environment variables
             sudo docker run -d --env-file /home/ubuntu/.env -p 5005:5005 440744253012.dkr.ecr.ap-south-1.amazonaws.com/backendforexfornepal:latest
